name: Pytest

on:
  push:
    branches:
      main
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/pytest.yml'
      - 'pytest.ini'

  pull_request:
    branches:
      main
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/pytest.yml'
      - 'pytest.ini'

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Use macos-13 to avoid arm64 architeture problem
        os: [ubuntu-latest, windows-latest, macos-13]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Run tests in Unix-like platform
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pytest -c pytest.ini
        if [ $? -ne 0 ]; then
          echo "::error title=Pytest failed::Tests failure"
          exit 1
        fi

    - name: Run tests in Windows platform
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pytest -c pytest.ini
        if ($LASTEXITCODE -ne 0) {
            Write-Host "::error title=Pytest failed::Tests failure"
            exit 1
        }
